// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_register_routes_cabi<T: Guest>() {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    T::register_routes();
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_db_setup_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::db_setup(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_execute_table_encryption_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::execute_table_encryption(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_read_encrypted_data_per_user_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::read_encrypted_data_per_user(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_avg_age_for_male_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::avg_age_for_male(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_avg_age_for_female_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::avg_age_for_female(_rt::string_lift(bytes0));
}
pub trait Guest {
    fn register_routes() -> ();
    fn db_setup(cmd: _rt::String) -> ();
    fn execute_table_encryption(cmd: _rt::String) -> ();
    fn read_encrypted_data_per_user(cmd: _rt::String) -> ();
    fn avg_age_for_male(cmd: _rt::String) -> ();
    fn avg_age_for_female(cmd: _rt::String) -> ();
}
#[doc(hidden)]
macro_rules! __export_world_klave_rust_postgre_template_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "register-routes")] unsafe extern "C" fn
        export_register_routes() { unsafe { $($path_to_types)*::
        _export_register_routes_cabi::<$ty > () } } #[unsafe (export_name = "db-setup")]
        unsafe extern "C" fn export_db_setup(arg0 : * mut u8, arg1 : usize,) { unsafe {
        $($path_to_types)*:: _export_db_setup_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "execute-table-encryption")] unsafe extern "C" fn
        export_execute_table_encryption(arg0 : * mut u8, arg1 : usize,) { unsafe {
        $($path_to_types)*:: _export_execute_table_encryption_cabi::<$ty > (arg0, arg1) }
        } #[unsafe (export_name = "read-encrypted-data-per-user")] unsafe extern "C" fn
        export_read_encrypted_data_per_user(arg0 : * mut u8, arg1 : usize,) { unsafe {
        $($path_to_types)*:: _export_read_encrypted_data_per_user_cabi::<$ty > (arg0,
        arg1) } } #[unsafe (export_name = "avg-age-for-male")] unsafe extern "C" fn
        export_avg_age_for_male(arg0 : * mut u8, arg1 : usize,) { unsafe {
        $($path_to_types)*:: _export_avg_age_for_male_cabi::<$ty > (arg0, arg1) } }
        #[unsafe (export_name = "avg-age-for-female")] unsafe extern "C" fn
        export_avg_age_for_female(arg0 : * mut u8, arg1 : usize,) { unsafe {
        $($path_to_types)*:: _export_avg_age_for_female_cabi::<$ty > (arg0, arg1) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_klave_rust_postgre_template_cabi;
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_klave_rust_postgre_template_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_klave_rust_postgre_template_cabi!($ty
        with_types_in $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_klave_rust_postgre_template_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:component:klave-ai-rag:klave-rust-postgre-template:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 361] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd7\x01\x01A\x02\x01\
A\x08\x01@\0\x01\0\x04\0\x0fregister-routes\x01\0\x01@\x01\x03cmds\x01\0\x04\0\x08\
db-setup\x01\x01\x04\0\x18execute-table-encryption\x01\x01\x04\0\x1cread-encrypt\
ed-data-per-user\x01\x01\x04\0\x10avg-age-for-male\x01\x01\x04\0\x12avg-age-for-\
female\x01\x01\x04\02component:klave-ai-rag/klave-rust-postgre-template\x04\0\x0b\
!\x01\0\x1bklave-rust-postgre-template\x03\0\0\0G\x09producers\x01\x0cprocessed-\
by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
