package component:{{project-name}};

/// An example world for the component to target.
world {{project-name}} {
    export register-routes: func();
    export load-from-ledger: func(cmd: string);
    export insert-in-ledger: func(cmd: string);
}
