package component:{{component_name}};

/// An example world for the component to target.
world {{component_name}} {
    export register-routes: func();
    export load-from-ledger: func(cmd: string);
    export insert-in-ledger: func(cmd: string);
}
